/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hadoop.practice;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
        System.out.println("testing");
    }
}
